[theme]
primaryColor = "#FFD700"                    # Gold
backgroundColor = "#1A1A2E"                 # Dark Navy
secondaryBackgroundColor = "#2E2E48"        # Deep Purple
textColor = "#FFFFFF"                       # White
font = "sans serif"
